os: Windows Server 2012 R2

configuration:
- Debug
- Release

platform:
- Win32
- x64

before_build:
- ps: >-
    Get-ChildItem . -include *.vcxproj.user -recurse | foreach ($_) {Remove-Item $_.FullName}

build:
  verbosity: detailed
